# Generated by Django 6.0.2 on 2026-02-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='donordonation',
            name='blood_group',
        ),
        migrations.AlterField(
            model_name='donordonation',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed')], default='completed', max_length=20),
        ),
    ]
