# Generated by Django 6.0.2 on 2026-02-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0001_initial'),
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmatch',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='donors.donor'),
        ),
        migrations.AddField(
            model_name='requestmatch',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='blood_requests.bloodrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='requestmatch',
            unique_together={('request', 'donor')},
        ),
    ]
