# Generated by Django 6.0.2 on 2026-02-08 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0002_initial'),
        ('donors', '0002_alter_donor_options_remove_donordonation_blood_group_and_more'),
        ('hospitals', '0002_alter_hospital_options_alter_hospital_licence_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='blood_type',
            new_name='blood_group',
        ),
        migrations.AlterUniqueTogether(
            name='requestmatch',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='requester_name',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests', to='hospitals.hospital'),
        ),
        migrations.AddConstraint(
            model_name='requestmatch',
            constraint=models.UniqueConstraint(fields=('request', 'donor'), name='unique_request_donor_match'),
        ),
    ]
