# Generated by Django 6.0.2 on 2026-02-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['hospital_name']},
        ),
        migrations.AlterField(
            model_name='hospital',
            name='licence_number',
            field=models.CharField(help_text='Government issued hospital licence number', max_length=50, unique=True),
        ),
    ]
